// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Car struct {
	ID        string `json:"id"`
	Make      string `json:"make"`
	Name      string `json:"name"`
	Available bool   `json:"available"`
}

type DeleteCar struct {
	CarID string `json:"carId"`
}

type EditCar struct {
	CarID     string `json:"carId"`
	Make      string `json:"make"`
	Name      string `json:"name"`
	Available bool   `json:"available"`
}

type Login struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type NewCar struct {
	Make      string `json:"make"`
	Name      string `json:"name"`
	Available bool   `json:"available"`
}

type NewUser struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type RefreshTokenInput struct {
	Token string `json:"token"`
}

type ReserveCar struct {
	CarID string `json:"carId"`
}

type ReturnCar struct {
	CarID string `json:"carId"`
}

type User struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Reservation *Car   `json:"reservation"`
}
